#  ______                 _
#  | ___ \               (_)
#  | |_/ /___ _ __   __ _ _ _ __
#  |    // _ \ '_ \ / _` | | '__|
#  | |\ \  __/ |_) | (_| | | |
#  \_| \_\___| .__/ \__,_|_|_|
#            | |
#            |_|  By @JackMD for PMMP
#
# Repair, a Repair plugin for PocketMine-MP
# Copyright (c) 2018 JackMD  < https://github.com/JackMD >
#
# Discord: JackMD#3717
# Twitter: JackMTaylor_
#
# This software is distributed under "GNU General Public License v3.0".
# This license allows you to use it and/or modify it but you are not at
# all allowed to sell this plugin at any cost. If found doing so the
# necessary action required would be taken.Further removal of the
# License and or author's name from this software is strictly prohibited.
#
# MysteryCrate is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License v3.0 for more details.
#
# You should have received a copy of the GNU General Public License v3.0
# along with this program. If not, see
# <https://opensource.org/licenses/GPL-3.0>.
#  -----------------------------------------------------------------------

# Decide whether or not you want to enable repair signs or not.
# Set to true to enable.
# Set to false to disable.
enableRepairSigns: true